# Generated by Django 5.1.1 on 2024-10-03 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0003_alter_payments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Выберите курс', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='materials.courses', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Выберите урок', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.lesson', verbose_name='Урок'),
        ),
    ]
