# Generated by Django 5.1.1 on 2024-10-18 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_courses_owner_lesson_owner'),
        ('users', '0007_subscription_delete_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Укажите сумму', verbose_name='Сумма оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания оплаты', null=True, verbose_name='Дата создания')),
                ('session_id', models.CharField(blank=True, help_text='Укажите id сессии', max_length=255, null=True, verbose_name='id сессии')),
                ('link', models.URLField(blank=True, help_text='Укажите ссылку на оплату', max_length=400, null=True, verbose_name='Ссылка на оплату')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_course', to='materials.courses', verbose_name='Курс')),
                ('user', models.ForeignKey(blank=True, help_text='Укажите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['user'],
            },
        ),
    ]
