# Generated by Django 5.1.1 on 2024-10-03 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Выберите Курс к уроку', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='materials.courses', verbose_name='Курс'),
        ),
    ]
